# Generated by Django 4.0 on 2022-05-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('color_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'ordering': ['color_id'],
            },
        ),
        migrations.CreateModel(
            name='Teas',
            fields=[
                ('tea_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('countries', models.TextField(blank=True, null=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea_app.colors')),
            ],
            options={
                'ordering': ['tea_id'],
            },
        ),
    ]
