# Generated by Django 4.0 on 2022-05-29 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('color_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('description_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teas',
            fields=[
                ('tea_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea_dir.colors')),
                ('countries', models.ManyToManyField(to='tea_dir.Countries')),
                ('description', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tea_dir.descriptions')),
            ],
        ),
    ]
